auth:
  enabled: False
  allowed_ips:
    - 192.168.1.56

#gpu环境 nvidia / ascend  / cpu
device_type: "nvidia"
device_ids: [0,1,2]

video:
  input_url: "rtsp://192.168.1.253:58554/live/ai2"
  rtmp: "rtmp://192.168.1.253:51935"
  width: 1280
  height: 720
  fps: 25
  bitrate: "2M"

model:
  path: "./models/VisDrone.onnx"
  input_size: [960, 960]
  conf_threshold: 0.3
  iou_threshold: 0.45

paths:
  # 指向ffmpeg
  ffmpeg_bin: "/usr/local/bin/ffmpeg"

draw_config:
  font_path: "./fonts/SimSun.ttf" # 字体路径
  font_size: 24  # 字体大小
  color: [0, 255, 0] # 字颜色

#labels: ['person','bicycle','car','motorcycle','airplane','bus','train','truck','boat','traffic light','fire hydrant','stop sign','parking meter','bench','bird','cat','dog','horse','sheep','cow','elephant','bear','zebra','giraffe','backpack','umbrella','handbag','tie','suitcase','frisbee','skis','snowboard','sports ball','kite','baseball bat','baseball glove','skateboard','surfboard','tennis racket','bottle','wine glass','cup','fork','knife','spoon','bowl','banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza','donut','cake','chair','couch','potted plant','bed','dining table','toilet','tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven','toaster','sink','refrigerator','book','clock','vase','scissors','teddy bear','hair drier','toothbrush']
#labels_zh: ['人', '自行车', '汽车', '摩托车', '飞机', '公共汽车', '火车', '卡车', '船', '交通信号灯', '消防栓', '停车标志', '停车计时器', '长椅', '鸟', '猫', '狗', '马', '羊', '牛', '大象', '熊', '斑马', '长颈鹿', '背包', '雨伞', '手提包', '领带', '手提箱', '飞盘', '滑雪板', '滑雪板', '运动球', '风筝', '棒球棒', '棒球手套', '滑板', '冲浪板', '网球拍', '瓶子', '高脚杯', '杯子', '叉子', '刀', '勺子', '碗', '香蕉', '苹果', '三明治', '橙子', '西兰花', '胡萝卜', '热狗', '披萨', '甜甜圈', '蛋糕', '椅子', '沙发', '盆栽植物', '床', '餐桌', '马桶', '电视机', '笔记本电脑', '鼠标', '遥控器', '键盘', '手机', '微波炉', '烤箱', '烤面包机', '水槽', '冰箱', '书', '钟表', '花瓶', '剪刀', '泰迪熊', '吹风机', '牙刷']

labels:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor

labels_zh:  
  0: 行人
  1: 人群
  2: 自行车
  3: 汽车
  4: 厢式货车
  5: 卡车
  6: 三轮车
  7: 带棚三轮车
  8: 公交车
  9: 摩托车